replicaCount: 1

image:
  repository: harbor.lhaidacher.com/onlineshop/inventory-service
  pullPolicy: IfNotPresent

imagePullSecrets:
- name: regcred

env:
  - name: SPRING_PROFILES_ACTIVE
    value: production

fullnameOverride: "inventory-service"

serviceAccount:
  create: true
  annotations: {}
  name: ""


service:
  type: ClusterIP
  port: 80
